//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WApp.WSDB {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSDB.BDSoap")]
    public interface BDSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataMovtos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataMovtos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataMovtos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataMovtosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarClave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsultarClave(string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarClave", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsultarClaveAsync(string Usr, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresaMovimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void IngresaMovimiento(string ID_CUENTA, string ID_MOVTO, double MONTO_MOVTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresaMovimiento", ReplyAction="*")]
        System.Threading.Tasks.Task IngresaMovimientoAsync(string ID_CUENTA, string ID_MOVTO, double MONTO_MOVTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BDSoapChannel : WApp.WSDB.BDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDSoapClient : System.ServiceModel.ClientBase<WApp.WSDB.BDSoap>, WApp.WSDB.BDSoap {
        
        public BDSoapClient() {
        }
        
        public BDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public System.Data.DataSet GetDataMovtos() {
            return base.Channel.GetDataMovtos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataMovtosAsync() {
            return base.Channel.GetDataMovtosAsync();
        }
        
        public string ConsultarClave(string Usr, string Pwd) {
            return base.Channel.ConsultarClave(Usr, Pwd);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarClaveAsync(string Usr, string Pwd) {
            return base.Channel.ConsultarClaveAsync(Usr, Pwd);
        }
        
        public void IngresaMovimiento(string ID_CUENTA, string ID_MOVTO, double MONTO_MOVTO) {
            base.Channel.IngresaMovimiento(ID_CUENTA, ID_MOVTO, MONTO_MOVTO);
        }
        
        public System.Threading.Tasks.Task IngresaMovimientoAsync(string ID_CUENTA, string ID_MOVTO, double MONTO_MOVTO) {
            return base.Channel.IngresaMovimientoAsync(ID_CUENTA, ID_MOVTO, MONTO_MOVTO);
        }
    }
}
